### ISSUE TITLE
NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by new-gen23** [lortas/Earthdawn-Character-Editor#4]
Getting the error:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

Might be related to Java version 11:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

> The JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9. In Java 11 they are completely removed from the JDK.

**Comment by lortas** [comment]
JAXB jars are now included. ECE should now run also with Java 11.
